name: quran
version: 1.0.0+1
publish_to: none

description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_qiblah: ^2.0.2
  flutter_svg: ^1.0.3
  geocoding: ^2.0.4
  get: 4.6.1
  location: ^4.3.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Arabic
      fonts:
        - asset: assets/fonts/sui.ttf
        - asset: assets/fonts/sui_bold.ttf
          weight: 700
