name: quran
version: 1.0.0+1
publish_to: none

description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_qiblah: ^2.0.2
  flutter_svg: ^1.0.3
  flutter_widget_from_html_core: ^0.8.5
  geocoding: ^2.0.4
  get: 4.6.1
  get_storage: ^2.0.3
  location: ^4.3.0
  map_launcher: ^2.2.1+1
  sizer: ^2.0.15
  supercharged: ^2.1.1
  visibility_detector: ^0.2.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_white.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/json/

  fonts:
    - family: Arabic
      fonts:
        - asset: assets/fonts/sui.ttf
        - asset: assets/fonts/sui_bold.ttf
          weight: 700

    - family: Quran
      fonts:
        - asset: assets/fonts/me_quran.ttf

flutter_intl:
  enabled: true
